### PR TITLE
Replace arrays with shorthand syntax.

### PR DESCRIPTION
**Pull request by DariusIII**

### CODE REVIEW

**Comment by Moinax** [comment]
Hi, sorry but until thetvdb.org releases his new API, I want to keep the code backward compatible.

When the new API will be available, I will make a v2 version and get rid of backward compatibility.

Thank you for your understanding.

Regards,

**Comment by DariusIII** [comment]
I understand. Is there any ETA on new API version from thetvdb?

**Comment by Moinax** [comment]
I don't know for sure, but you can follow the topic on their forum https://forums.thetvdb.com/viewtopic.php?t=22325

**Comment by DariusIII** [comment]
Was looking at it after i wrote the comment. Thank you for the info and have a great day.

**Pull request closed without merging**
